export const APPLICATION_BOOTING = 'APPLICATION_BOOTING'
export const APPLICATION_INITIALIZED = 'APPLICATION_INITIALIZED'
export const APPLICATION_RELOAD = 'APPLICATION_RELOAD'

export const CHANGE_ROUTE = 'CHANGE_ROUTE'

